
from __future__ import annotations

import argparse
import hashlib
import json
import math
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import simpy


RANDOM_SEED = 42
SIMULATOR_VERSION = "2026.09-large-hospital-v3"
FIXED_ICU_RISK_THRESHOLD = 0.50
BASELINE_MAX_PATIENTS = 500
BASELINE_TARGET_UTILIZATION = 0.75
BASELINE_TARGET_UTILIZATION_RANGE = (0.75, 0.80)
HOSPITAL_SCALE_MULTIPLIER = 3.0
GA_MIN_CAPACITY_FACTOR = 0.70
GA_MAX_CAPACITY_FACTOR = 1.30


@dataclass
class HospitalPolicy:
    icu_beds: int
    general_beds: int
    doctors: int
    nurses: int
    icu_risk_threshold: float = FIXED_ICU_RISK_THRESHOLD


def derive_ga_bounds(
    baseline_policy: dict | HospitalPolicy,
    minimum_factor: float = GA_MIN_CAPACITY_FACTOR,
    maximum_factor: float = GA_MAX_CAPACITY_FACTOR,
) -> dict[str, tuple[int, int]]:
    """Build an integer GA search envelope relative to baseline capacity."""
    if not (0 < minimum_factor <= 1.0 <= maximum_factor):
        raise ValueError("GA bound factors must bracket the baseline capacity.")

    sensible_minimums = {
        "icu_beds": 1,
        "general_beds": 1,
        "doctors": 1,
        "nurses": 1,
    }
    bounds = {}
    for key, sensible_minimum in sensible_minimums.items():
        value = (
            getattr(baseline_policy, key)
            if isinstance(baseline_policy, HospitalPolicy)
            else baseline_policy[key]
        )
        capacity = max(sensible_minimum, int(value))
        low = max(sensible_minimum, int(math.floor(capacity * minimum_factor)))
        high = max(low, int(math.ceil(capacity * maximum_factor)))
        bounds[key] = (low, high)
    return bounds


def file_sha256(path: Path) -> str:
    """Return a stable fingerprint used to detect stale result artifacts."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def select_patient_cohort(
    df: pd.DataFrame,
    max_patients: int,
) -> tuple[pd.DataFrame, str]:
    """Select a reproducible cohort, preferring the earliest arrivals."""
    if max_patients <= 0 or len(df) <= max_patients:
        return df.copy(), "all_rows"

    if "arrival_time" in df.columns:
        out = df.copy()
        out["_arrival_sort"] = pd.to_datetime(
            out["arrival_time"],
            errors="coerce",
        )
        out = (
            out.sort_values("_arrival_sort", na_position="last")
            .head(max_patients)
            .drop(columns="_arrival_sort")
            .copy()
        )
        return out, "earliest_arrivals"

    return df.head(max_patients).copy(), "first_rows"


def validate_baseline_artifact(
    metrics: dict,
    input_path: Path,
    model_path: Path,
) -> list[str]:
    """Validate baseline provenance and basic metric sanity for the dashboard."""
    errors: list[str] = []
    metadata = metrics.get("baseline_metadata", {})
    policy = metrics.get("policy", {})

    if metadata.get("schema_version") != 3:
        errors.append("baseline metadata is missing or uses an unsupported schema")
    if metadata.get("simulator_version") != SIMULATOR_VERSION:
        errors.append("baseline was generated by a different simulator version")

    methodology = metadata.get("capacity_methodology", {})
    derived_capacity = methodology.get("derived_capacity", {})
    offered_load = methodology.get("offered_concurrent_load", {})
    if metadata.get("capacity_mode") != "derived":
        errors.append("baseline capacity was manually overridden")
    try:
        scale_matches = np.isclose(
            float(metadata.get("hospital_scale_multiplier", -1)),
            HOSPITAL_SCALE_MULTIPLIER,
        )
    except (TypeError, ValueError):
        scale_matches = False
    if not scale_matches:
        errors.append("baseline hospital workload scale is not canonical")

    scaling = methodology.get("workload_scaling", {})
    if scaling.get("method") != "deterministic_arrival_time_compression":
        errors.append("baseline workload-scaling method is not canonical")
    try:
        methodology_scale_matches = np.isclose(
            float(scaling.get("hospital_scale_multiplier", -1)),
            HOSPITAL_SCALE_MULTIPLIER,
        )
    except (TypeError, ValueError):
        methodology_scale_matches = False
    if not methodology_scale_matches:
        errors.append("baseline capacity methodology uses the wrong workload scale")
    if methodology.get("method") != "offered_load_target_utilization":
        errors.append("baseline does not use the canonical demand-based method")
    try:
        target_matches = np.isclose(
            float(methodology.get("target_utilization", -1)),
            BASELINE_TARGET_UTILIZATION,
        )
    except (TypeError, ValueError):
        target_matches = False
    if not target_matches:
        errors.append("baseline target utilization is not canonical")
    if methodology.get("rounding") != "ceiling":
        errors.append("baseline capacity rounding method is not canonical")

    for key in ["icu_beds", "general_beds", "doctors", "nurses"]:
        actual = policy.get(key)
        expected = derived_capacity.get(key)
        try:
            matches = np.isclose(float(actual), float(expected))
        except (TypeError, ValueError):
            matches = False
        if not matches:
            errors.append(f"baseline policy does not match derived {key}")

        try:
            recomputed = math.ceil(
                float(offered_load[key]) / BASELINE_TARGET_UTILIZATION
            )
            formula_matches = int(expected) == recomputed
        except (KeyError, TypeError, ValueError, OverflowError):
            formula_matches = False
        if not formula_matches:
            errors.append(f"derived {key} does not match the capacity formula")

    try:
        recorded_bounds = methodology["ga_search_envelope"]["bounds"]
        expected_bounds = derive_ga_bounds(policy)
        bounds_match = all(
            list(expected_bounds[key]) == list(recorded_bounds[key])
            for key in expected_bounds
        )
    except (KeyError, TypeError, ValueError):
        bounds_match = False
    if not bounds_match:
        errors.append("baseline GA search envelope is missing or inconsistent")

    try:
        threshold_matches = np.isclose(
            float(policy.get("icu_risk_threshold", -1)),
            FIXED_ICU_RISK_THRESHOLD,
        )
    except (TypeError, ValueError):
        threshold_matches = False
    if not threshold_matches:
        errors.append("baseline does not use the fixed RF threshold")

    cohort = metadata.get("cohort", {})
    if cohort.get("max_patients") != BASELINE_MAX_PATIENTS:
        errors.append("baseline cohort size does not match the canonical configuration")
    if cohort.get("selection") != "earliest_arrivals":
        errors.append("baseline cohort was not selected by earliest arrival")

    expected_files = {
        "data_sha256": input_path,
        "model_sha256": model_path,
        "simulator_sha256": Path(__file__).resolve(),
    }
    for key, path in expected_files.items():
        if not path.exists():
            errors.append(f"required baseline dependency is missing: {path.name}")
        elif metadata.get(key) != file_sha256(path):
            errors.append(f"baseline is stale because {path.name} changed")

    required_metrics = [
        "patients_completed",
        "mean_waiting_time_min",
        "median_waiting_time_min",
        "p95_waiting_time_min",
        "high_risk_mean_waiting_time_min",
        "throughput_patients_per_day",
        "icu_bed_utilization",
        "general_bed_utilization",
        "doctor_utilization",
        "nurse_utilization",
        "simulation_duration_days",
    ]
    for key in required_metrics:
        try:
            value = float(metrics[key])
            if not np.isfinite(value) or value < 0:
                raise ValueError
        except (KeyError, TypeError, ValueError):
            errors.append(f"baseline metric is missing or invalid: {key}")

    selected = cohort.get("selected_patients")
    if selected != BASELINE_MAX_PATIENTS:
        errors.append("baseline metadata has an unexpected selected-patient count")
    if metrics.get("patients_completed") != selected:
        errors.append("baseline did not complete the recorded patient cohort")

    for key in [
        "icu_bed_utilization",
        "general_bed_utilization",
        "doctor_utilization",
        "nurse_utilization",
    ]:
        try:
            if float(metrics[key]) > 1.0:
                errors.append(f"baseline utilization is outside [0, 1]: {key}")
        except (KeyError, TypeError, ValueError):
            pass

    return errors


def add_random_forest_predictions(
    df: pd.DataFrame,
    model_path: Path | None,
) -> pd.DataFrame:
    """
    Adds predicted risk and probability from the trained Random Forest.
    If no model is supplied, falls back to the synthetic target only so
    that the simulator can still be tested independently.
    """
    out = df.copy()

    if model_path is not None and model_path.exists():
        pipeline = joblib.load(model_path)
        prob = pipeline.predict_proba(out)[:, 1]
        pred = (prob >= 0.50).astype(int)

        out["predicted_high_resource_need"] = pred
        out["predicted_probability"] = prob
    else:
        if "high_resource_need" not in out.columns:
            raise ValueError(
                "No Random Forest model was found and the dataset has no "
                "'high_resource_need' fallback column."
            )

        fallback = pd.to_numeric(
            out["high_resource_need"], errors="coerce"
        ).fillna(0).astype(int)

        out["predicted_high_resource_need"] = fallback
        out["predicted_probability"] = fallback.astype(float)

    return out


def prepare_arrival_offsets(
    df: pd.DataFrame,
    workload_scale: float = HOSPITAL_SCALE_MULTIPLIER,
) -> pd.DataFrame:
    """
    Convert arrivals to minutes and deterministically compress their timeline.

    Dividing every offset by the workload scale preserves patient order and all
    clinical/service-time distributions while increasing arrival demand by the
    requested multiplier without duplicating simulation records.
    """
    if workload_scale <= 0:
        raise ValueError("Workload scale must be greater than zero.")
    out = df.copy()

    if "arrival_time" not in out.columns:
        # Fallback: Poisson-like arrival spacing.
        rng = np.random.default_rng(RANDOM_SEED)
        intervals = rng.exponential(scale=60.0, size=len(out))
        out["arrival_offset_min"] = np.cumsum(intervals) / workload_scale
        return out

    arrival = pd.to_datetime(out["arrival_time"], errors="coerce")
    valid = arrival.dropna()

    if valid.empty:
        rng = np.random.default_rng(RANDOM_SEED)
        intervals = rng.exponential(scale=60.0, size=len(out))
        out["arrival_offset_min"] = np.cumsum(intervals) / workload_scale
        return out

    first = valid.min()
    out["arrival_offset_min"] = (arrival - first).dt.total_seconds() / 60.0

    # Any missing timestamps are placed after the latest valid arrival.
    if out["arrival_offset_min"].isna().any():
        rng = np.random.default_rng(RANDOM_SEED)
        latest = float(out["arrival_offset_min"].max())
        missing_count = int(out["arrival_offset_min"].isna().sum())
        filler = latest + np.cumsum(
            rng.exponential(scale=60.0, size=missing_count)
        )
        out.loc[out["arrival_offset_min"].isna(), "arrival_offset_min"] = filler

    out["arrival_offset_min"] = out["arrival_offset_min"] / workload_scale

    return out.sort_values("arrival_offset_min").reset_index(drop=True)


def derive_baseline_policy(
    patient_df: pd.DataFrame,
    target_utilization: float = BASELINE_TARGET_UTILIZATION,
    workload_scale: float = HOSPITAL_SCALE_MULTIPLIER,
) -> tuple[HospitalPolicy, dict]:
    """Derive deterministic capacity from offered concurrent workload."""
    if not (
        BASELINE_TARGET_UTILIZATION_RANGE[0]
        <= target_utilization
        <= BASELINE_TARGET_UTILIZATION_RANGE[1]
    ):
        raise ValueError("Baseline target utilization must be between 0.75 and 0.80.")
    if patient_df.empty:
        raise ValueError("Cannot derive baseline capacity from an empty cohort.")

    patients = prepare_arrival_offsets(patient_df, workload_scale)
    arrival_span_min = max(
        float(patients["arrival_offset_min"].max())
        - float(patients["arrival_offset_min"].min()),
        1.0,
    )

    treatment = pd.to_numeric(
        patients.get(
            "treatment_time_min",
            pd.Series(np.nan, index=patients.index),
        ),
        errors="coerce",
    ).fillna(120.0).clip(15.0, 720.0)

    los_hours = pd.to_numeric(
        patients.get(
            "length_of_stay_hours",
            pd.Series(np.nan, index=patients.index),
        ),
        errors="coerce",
    )
    fallback_los_hours = np.maximum(treatment / 60.0, 6.0)
    los_minutes = (
        los_hours.fillna(fallback_los_hours) * 60.0
    ).clip(lower=treatment, upper=14 * 24 * 60.0)

    risk = pd.to_numeric(
        patients.get(
            "predicted_probability",
            pd.Series(0.0, index=patients.index),
        ),
        errors="coerce",
    ).fillna(0.0)
    icu_mask = risk >= FIXED_ICU_RISK_THRESHOLD

    offered_load = {
        "icu_beds": float(los_minutes[icu_mask].sum() / arrival_span_min),
        "general_beds": float(los_minutes[~icu_mask].sum() / arrival_span_min),
        "doctors": float(treatment.sum() / arrival_span_min),
        "nurses": float(treatment.sum() / arrival_span_min),
    }
    capacity = {
        key: max(1, int(math.ceil(value / target_utilization)))
        for key, value in offered_load.items()
    }
    implied_utilization = {
        key: offered_load[key] / capacity[key]
        for key in offered_load
    }

    policy = HospitalPolicy(
        **capacity,
        icu_risk_threshold=FIXED_ICU_RISK_THRESHOLD,
    )
    ga_bounds = derive_ga_bounds(policy)
    methodology = {
        "method": "offered_load_target_utilization",
        "formula": "capacity = ceil(offered_concurrent_load / target_utilization)",
        "target_utilization": target_utilization,
        "target_utilization_range": list(BASELINE_TARGET_UTILIZATION_RANGE),
        "rounding": "ceiling",
        "workload_scaling": {
            "method": "deterministic_arrival_time_compression",
            "hospital_scale_multiplier": workload_scale,
            "formula": (
                "scaled_arrival_offset = original_arrival_offset / "
                "hospital_scale_multiplier"
            ),
            "records_duplicated": False,
            "preserved_attributes": [
                "patient characteristics",
                "Random Forest predictions",
                "treatment durations",
                "length-of-stay durations",
                "arrival ordering",
            ],
        },
        "unscaled_arrival_span_minutes": round(
            arrival_span_min * workload_scale,
            3,
        ),
        "arrival_span_minutes": round(arrival_span_min, 3),
        "arrival_span_days": round(arrival_span_min / (24 * 60), 3),
        "offered_concurrent_load": {
            key: round(value, 6)
            for key, value in offered_load.items()
        },
        "derived_capacity": capacity,
        "ga_search_envelope": {
            "minimum_factor": GA_MIN_CAPACITY_FACTOR,
            "maximum_factor": GA_MAX_CAPACITY_FACTOR,
            "rounding": "floor minimum; ceiling maximum",
            "bounds": {
                key: list(value)
                for key, value in ga_bounds.items()
            },
        },
        "implied_target_utilization": {
            key: round(value, 6)
            for key, value in implied_utilization.items()
        },
        "assumptions": {
            "icu_beds": "RF probability >= 0.50; occupied for full length of stay",
            "general_beds": "RF probability < 0.50; occupied for full length of stay",
            "doctors": "one doctor per patient during treatment duration",
            "nurses": "one nurse per patient during treatment duration",
        },
        "patient_counts": {
            "icu": int(icu_mask.sum()),
            "general": int((~icu_mask).sum()),
        },
    }
    return policy, methodology


class HealthcareDigitalTwin:
    """
    Discrete-event hospital Digital Twin using SimPy.

    Each patient requires:
      - one bed (ICU or general)
      - one doctor
      - one nurse

    The patient waits until all required resources are available, receives
    treatment, and then releases the resources.
    """

    def __init__(
        self,
        env: simpy.Environment,
        policy: HospitalPolicy,
    ) -> None:
        self.env = env
        self.policy = policy

        self.icu_beds = simpy.PriorityResource(
            env, capacity=max(1, int(policy.icu_beds))
        )
        self.general_beds = simpy.PriorityResource(
            env, capacity=max(1, int(policy.general_beds))
        )
        self.doctors = simpy.PriorityResource(
            env, capacity=max(1, int(policy.doctors))
        )
        self.nurses = simpy.PriorityResource(
            env, capacity=max(1, int(policy.nurses))
        )

        self.results: list[dict] = []

        self.busy_minutes = {
            "icu_beds": 0.0,
            "general_beds": 0.0,
            "doctors": 0.0,
            "nurses": 0.0,
        }

    @staticmethod
    def _priority_from_row(row: pd.Series) -> int:
        """
        SimPy PriorityResource: lower number = higher priority.
        """
        if "priority_level" in row and pd.notna(row["priority_level"]):
            try:
                return int(np.clip(int(row["priority_level"]), 1, 5))
            except Exception:
                pass

        # Derive priority from predicted risk when explicit priority is absent.
        risk = float(row.get("predicted_probability", 0.0))
        if risk >= 0.80:
            return 1
        if risk >= 0.60:
            return 2
        if risk >= 0.40:
            return 3
        if risk >= 0.20:
            return 4
        return 5

    def patient_process(self, row: pd.Series):
        patient_id = row.get(
            "synthetic_patient_id",
            row.get("patientunitstayid", len(self.results) + 1),
        )

        risk_prob = float(
            pd.to_numeric(
                pd.Series([row.get("predicted_probability", 0.0)]),
                errors="coerce",
            ).fillna(0).iloc[0]
        )

        needs_icu = risk_prob >= self.policy.icu_risk_threshold
        bed_resource = self.icu_beds if needs_icu else self.general_beds
        bed_name = "ICU" if needs_icu else "General"

        priority = self._priority_from_row(row)

        treatment_time = pd.to_numeric(
            pd.Series([row.get("treatment_time_min", np.nan)]),
            errors="coerce",
        ).iloc[0]

        if pd.isna(treatment_time):
            treatment_time = 120.0

        treatment_time = float(np.clip(treatment_time, 15.0, 720.0))

        arrival_time = float(row["arrival_offset_min"])
        if self.env.now < arrival_time:
            yield self.env.timeout(arrival_time - self.env.now)

        entered_queue = self.env.now

        # Hospital bed is occupied for the patient's length of stay, while
        # doctor/nurse resources are used for the active treatment period.
        los_hours = pd.to_numeric(
            pd.Series([row.get("length_of_stay_hours", np.nan)]),
            errors="coerce",
        ).iloc[0]

        if pd.isna(los_hours):
            los_hours = max(treatment_time / 60.0, 6.0)

        los_minutes = float(np.clip(los_hours * 60.0, treatment_time, 14 * 24 * 60.0))

        # First wait for an appropriate bed.
        with bed_resource.request(priority=priority) as bed_req:
            yield bed_req
            bed_acquired_time = self.env.now

            # Then wait for clinical staff to begin treatment.
            with self.doctors.request(priority=priority) as doctor_req, \
                 self.nurses.request(priority=priority) as nurse_req:

                yield simpy.events.AllOf(
                    self.env,
                    [doctor_req, nurse_req],
                )

                treatment_start = self.env.now
                waiting_time = treatment_start - entered_queue

                yield self.env.timeout(treatment_time)

                self.busy_minutes["doctors"] += treatment_time
                self.busy_minutes["nurses"] += treatment_time

            # Bed remains occupied for the rest of the stay.
            elapsed_in_bed = self.env.now - bed_acquired_time
            remaining_los = max(0.0, los_minutes - elapsed_in_bed)

            if remaining_los > 0:
                yield self.env.timeout(remaining_los)

            discharge_time = self.env.now

            if needs_icu:
                self.busy_minutes["icu_beds"] += los_minutes
            else:
                self.busy_minutes["general_beds"] += los_minutes

            self.results.append(
                {
                    "patient_id": patient_id,
                    "arrival_min": round(arrival_time, 2),
                    "priority": priority,
                    "predicted_probability": round(risk_prob, 4),
                    "bed_type": bed_name,
                    "waiting_time_min": round(waiting_time, 2),
                    "treatment_time_min": round(treatment_time, 2),
                    "length_of_stay_min": round(los_minutes, 2),
                    "discharge_min": round(discharge_time, 2),
                }
            )

    def run(self, patients: pd.DataFrame) -> None:
        for _, row in patients.iterrows():
            self.env.process(self.patient_process(row))

        self.env.run()

    def calculate_metrics(self) -> dict:
        result_df = pd.DataFrame(self.results)

        if result_df.empty:
            return {
                "patients_completed": 0,
                "mean_waiting_time_min": None,
                "median_waiting_time_min": None,
                "p95_waiting_time_min": None,
                "throughput_patients_per_day": 0.0,
                "icu_bed_utilization": 0.0,
                "general_bed_utilization": 0.0,
                "doctor_utilization": 0.0,
                "nurse_utilization": 0.0,
            }

        start = float(result_df["arrival_min"].min())
        end = float(result_df["discharge_min"].max())
        duration = max(end - start, 1.0)

        def utilization(key: str, capacity: int) -> float:
            denom = duration * max(1, capacity)
            return float(min(self.busy_minutes[key] / denom, 1.0))

        days = duration / (24 * 60)

        high_risk = result_df[result_df["predicted_probability"] >= 0.50]

        return {
            "patients_completed": int(len(result_df)),
            "mean_waiting_time_min": round(
                float(result_df["waiting_time_min"].mean()), 3
            ),
            "median_waiting_time_min": round(
                float(result_df["waiting_time_min"].median()), 3
            ),
            "p95_waiting_time_min": round(
                float(result_df["waiting_time_min"].quantile(0.95)), 3
            ),
            "high_risk_mean_waiting_time_min": round(
                float(high_risk["waiting_time_min"].mean()), 3
            ) if not high_risk.empty else None,
            "throughput_patients_per_day": round(
                float(len(result_df) / max(days, 1e-6)), 3
            ),
            "icu_bed_utilization": round(
                utilization("icu_beds", self.policy.icu_beds), 4
            ),
            "general_bed_utilization": round(
                utilization("general_beds", self.policy.general_beds), 4
            ),
            "doctor_utilization": round(
                utilization("doctors", self.policy.doctors), 4
            ),
            "nurse_utilization": round(
                utilization("nurses", self.policy.nurses), 4
            ),
            "simulation_duration_days": round(days, 3),
        }


def simulate_hospital(
    patient_df: pd.DataFrame,
    policy: HospitalPolicy,
    workload_scale: float = HOSPITAL_SCALE_MULTIPLIER,
) -> tuple[dict, pd.DataFrame]:
    """
    Reusable function for the future Genetic Algorithm.
    """
    patients = prepare_arrival_offsets(patient_df, workload_scale)

    env = simpy.Environment()
    twin = HealthcareDigitalTwin(env, policy)
    twin.run(patients)

    metrics = twin.calculate_metrics()
    results = pd.DataFrame(twin.results)

    return metrics, results


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run the Healthcare Digital Twin baseline simulation."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("data/synthetic/synthetic_hospital.csv"),
    )
    parser.add_argument(
        "--model",
        type=Path,
        default=Path("models/random_forest_pipeline.joblib"),
    )
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=Path("results/digital_twin"),
    )

    parser.add_argument(
        "--icu-beds",
        type=int,
        default=None,
        help="Optional manual override; omit all resource flags for canonical derivation.",
    )
    parser.add_argument(
        "--general-beds",
        type=int,
        default=None,
    )
    parser.add_argument("--doctors", type=int, default=None)
    parser.add_argument("--nurses", type=int, default=None)
    parser.add_argument(
        "--icu-risk-threshold",
        type=float,
        default=FIXED_ICU_RISK_THRESHOLD,
    )
    parser.add_argument(
        "--max-patients",
        type=int,
        default=BASELINE_MAX_PATIENTS,
        help=(
            "Canonical baseline cohort size. Use 0 only for an explicit "
            "non-dashboard full-dataset experiment."
        ),
    )
    parser.add_argument(
        "--workload-scale",
        type=float,
        default=HOSPITAL_SCALE_MULTIPLIER,
        help="Deterministic multiplier applied by compressing arrival offsets.",
    )

    args = parser.parse_args()
    args.results_dir.mkdir(parents=True, exist_ok=True)

    print(f"Loading patient data: {args.input}")
    source_df = pd.read_csv(args.input, low_memory=False)
    df, cohort_selection = select_patient_cohort(
        source_df,
        args.max_patients,
    )

    if not np.isclose(args.icu_risk_threshold, FIXED_ICU_RISK_THRESHOLD):
        raise ValueError(
            "The Digital Twin baseline uses the fixed Random Forest threshold "
            f"{FIXED_ICU_RISK_THRESHOLD:.2f}."
        )

    print("Adding Random Forest risk/resource predictions...")
    df = add_random_forest_predictions(df, args.model)

    derived_policy, capacity_methodology = derive_baseline_policy(
        df,
        workload_scale=args.workload_scale,
    )
    manual_capacity = {
        "icu_beds": args.icu_beds,
        "general_beds": args.general_beds,
        "doctors": args.doctors,
        "nurses": args.nurses,
    }
    supplied = [value is not None for value in manual_capacity.values()]
    if any(supplied) and not all(supplied):
        raise ValueError(
            "Supply all four resource overrides or omit all four to derive "
            "the canonical demand-based baseline."
        )

    if all(supplied):
        policy = HospitalPolicy(
            **{key: int(value) for key, value in manual_capacity.items()},
            icu_risk_threshold=args.icu_risk_threshold,
        )
        capacity_mode = "manual_override"
    else:
        policy = derived_policy
        capacity_mode = "derived"

    print("Baseline capacity methodology:")
    print(json.dumps(capacity_methodology, indent=2))
    print(f"Capacity mode: {capacity_mode}")

    print("Running SimPy Healthcare Digital Twin...")
    metrics, patient_results = simulate_hospital(
        df,
        policy,
        workload_scale=args.workload_scale,
    )

    metrics["policy"] = {
        "icu_beds": policy.icu_beds,
        "general_beds": policy.general_beds,
        "doctors": policy.doctors,
        "nurses": policy.nurses,
        "icu_risk_threshold": policy.icu_risk_threshold,
    }

    arrival_span_days = max(
        (
            float(patient_results["arrival_min"].max())
            - float(patient_results["arrival_min"].min())
        ) / (24 * 60),
        1 / (24 * 60),
    )
    bed_load = (
        patient_results.groupby("bed_type")["length_of_stay_min"]
        .agg(["count", "sum"])
    )

    def load_value(bed_type: str, column: str) -> float:
        if bed_type not in bed_load.index:
            return 0.0
        return float(bed_load.loc[bed_type, column])

    metrics["baseline_metadata"] = {
        "schema_version": 3,
        "simulator_version": SIMULATOR_VERSION,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(
            timespec="seconds"
        ),
        "random_seed": RANDOM_SEED,
        "hospital_scale_multiplier": float(args.workload_scale),
        "capacity_mode": capacity_mode,
        "capacity_methodology": capacity_methodology,
        "cohort": {
            "selection": cohort_selection,
            "max_patients": int(args.max_patients),
            "source_rows": int(len(source_df)),
            "selected_patients": int(len(df)),
            "arrival_span_days": round(arrival_span_days, 3),
        },
        "simulation": {
            "patient_count": int(len(df)),
            "arrival_span_minutes": round(arrival_span_days * 24 * 60, 3),
            "simulation_duration_days": metrics["simulation_duration_days"],
        },
        "load_profile": {
            "icu_patients": int(load_value("ICU", "count")),
            "general_patients": int(load_value("General", "count")),
            "average_icu_beds_required_during_arrivals": round(
                load_value("ICU", "sum") / (24 * 60) / arrival_span_days,
                3,
            ),
            "average_general_beds_required_during_arrivals": round(
                load_value("General", "sum") / (24 * 60) / arrival_span_days,
                3,
            ),
            "average_doctors_required_during_arrivals": round(
                float(patient_results["treatment_time_min"].sum())
                / (24 * 60)
                / arrival_span_days,
                3,
            ),
            "average_nurses_required_during_arrivals": round(
                float(patient_results["treatment_time_min"].sum())
                / (24 * 60)
                / arrival_span_days,
                3,
            ),
        },
        "data_path": args.input.as_posix(),
        "data_sha256": file_sha256(args.input),
        "model_path": args.model.as_posix(),
        "model_sha256": file_sha256(args.model),
        "simulator_path": Path(__file__).resolve().relative_to(
            Path.cwd().resolve()
        ).as_posix(),
        "simulator_sha256": file_sha256(Path(__file__).resolve()),
    }

    with open(
        args.results_dir / "baseline_metrics.json",
        "w",
        encoding="utf-8",
    ) as f:
        json.dump(metrics, f, indent=2)

    patient_results.to_csv(
        args.results_dir / "patient_simulation_results.csv",
        index=False,
    )

    print("\nDigital Twin complete.")
    print(json.dumps(metrics, indent=2))
    print(f"\nResults saved to: {args.results_dir}")


if __name__ == "__main__":
    main()
